server:
  port: 8088

api:
  prefix: /api/v1

spring:
  datasource:
      url: jdbc:mysql://music-web-hk241-tai21042004.i.aivencloud.com:23837/music_web_db?ssl-mode=REQUIRED
      username: CO3103-HK241
      password: AVNS_6A1ZeHxJ0TxZiMoL2Dh
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


cloudinary:
  cloud_name: tantai21042004
  api_key: 395294154562735
  api_secret: B9-0yO18W_3W7CyDcjAQMquRgo4

jwt:
  expiration: 7200 # 2 hours
  expiration-refresh-token: 5184000 # 60 days (2 months)  
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

    